ALTER TABLE maxbattle DROP COLUMN override_areas, DROP COLUMN override_location_label;
ALTER TABLE forts     DROP COLUMN override_areas, DROP COLUMN override_location_label;
ALTER TABLE gym       DROP COLUMN override_areas, DROP COLUMN override_location_label;
ALTER TABLE nests     DROP COLUMN override_areas, DROP COLUMN override_location_label;
ALTER TABLE lures     DROP COLUMN override_areas, DROP COLUMN override_location_label;
ALTER TABLE invasion  DROP COLUMN override_areas, DROP COLUMN override_location_label;
ALTER TABLE quest     DROP COLUMN override_areas, DROP COLUMN override_location_label;
ALTER TABLE egg       DROP COLUMN override_areas, DROP COLUMN override_location_label;
ALTER TABLE raid      DROP COLUMN override_areas, DROP COLUMN override_location_label;
ALTER TABLE monsters  DROP COLUMN override_areas, DROP COLUMN override_location_label;
DROP TABLE user_locations;
