const Controller = require('./controller')
const nightTime = require('./common/nightTime')

class Weather extends Controller {
	/**
	 * Handle a pre-matched weather change from the processor.
	 * matchedUsers: [{id, name, type, language, template, clean, ping, active_pokemons}]
	 * matchedAreas: [{name, displayInMatches, group}]
	 */
	async handleMatched(obj, matchedUsers, matchedAreas) {
		const data = obj
		try {
			// locale handled by Go processor
			const logReference = data.s2_cell_id

			// Static map tile generation (including per-user pokemon tiles) is now
			// handled by the Go processor enrichment. The URL arrives in data.staticMap.

			this.log.info(`${logReference}: Weather change received from processor: ${data.old_gameplay_condition} -> ${data.gameplay_condition} (source=${data.source})`)

			nightTime.setNightTime(data, this.config)

			data.oldWeatherId = data.old_gameplay_condition > 0 ? data.old_gameplay_condition : ''
			data.weatherId = data.gameplay_condition ? data.gameplay_condition : ''
			data.condition = data.gameplay_condition

			data.matchedAreas = matchedAreas.map((a) => ({ name: a.name, displayInMatches: a.displayInMatches, group: a.group }))
			data.matched = data.matchedAreas.map((x) => x.name.toLowerCase())
			// Icon URLs are pre-computed by the processor enrichment

			const jobs = []
			// weatherTth is pre-computed by the Go processor
			const weatherTth = data.weatherTth || { hours: 0, minutes: 0, seconds: 0 }

			for (const cares of matchedUsers) {
				this.log.debug(`${logReference}: Weather alert being generated for ${cares.id} ${cares.name} ${cares.type} ${cares.language} ${cares.template}`)

				// Populate activePokemons from processor payload
				// Active pokemon icon URLs are pre-computed by the processor enrichment
				if (cares.active_pokemons && cares.active_pokemons.length > 0) {
					data.activePokemons = cares.active_pokemons.slice()
				} else {
					data.activePokemons = null
				}

				// Per-user static map with active pokemon is now generated by processor
				// enrichment (per-language enrichment includes staticMap when
				// show_altered_pokemon_static_map is enabled).
				const langEnrichmentForTile = this.getLanguageEnrichment(data, cares.language || this.config.general.locale)
				if (langEnrichmentForTile.staticMap) {
					data.staticMap = langEnrichmentForTile.staticMap
				}
				data.staticmap = data.staticMap // deprecated

				const language = cares.language || this.config.general.locale
				const translator = this.translatorFactory.Translator(language)
				let [platform] = cares.type.split(':')
				if (platform === 'webhook') platform = 'discord'

				// Pre-translated weather names and active pokemon from processor
				const langEnrichment = this.getLanguageEnrichment(data, language)
				data.oldWeatherName = langEnrichment.oldWeatherName || ''
				data.weatherName = langEnrichment.weatherName || ''
				data.oldWeatherEmoji = langEnrichment.oldWeatherEmojiKey ? translator.translate(this.emojiLookup.lookup(langEnrichment.oldWeatherEmojiKey, platform)) : ''
				data.weatherEmoji = langEnrichment.weatherEmojiKey ? translator.translate(this.emojiLookup.lookup(langEnrichment.weatherEmojiKey, platform)) : ''
				data.weatherCellId = data.s2_cell_id

				// Active pokemon with pre-translated names from processor
				if (langEnrichment.enrichedActivePokemons && langEnrichment.enrichedActivePokemons.length > 0) {
					data.activePokemons = langEnrichment.enrichedActivePokemons.slice()
				}

				data.weather = data.weatherName // deprecated
				data.oldweather = data.oldWeatherName // deprecated
				data.oldweatheremoji = data.oldWeatherEmoji // deprecated
				data.weatheremoji = data.weatherEmoji // deprecated

				const view = {
					...data,
					id: data.s2_cell_id,
					areas: data.matchedAreas.filter((area) => area.displayInMatches).map((area) => area.name).join(', '),
					now: new Date(),
					nowISO: new Date().toISOString(),
				}

				const templateType = 'weatherchange'
				const mustacheTemplate = this.getDts(logReference, templateType, platform, cares.template, language)
				let message
				if (mustacheTemplate) {
					let mustacheResult
					try {
						mustacheResult = mustacheTemplate(view, { data: { language, platform } })
					} catch (err) {
						this.log.error(`${logReference}: Error generating mustache results for ${platform}/${cares.template}/${language}`, err, view)
					}
					if (mustacheResult) {
						mustacheResult = await this.urlShorten(mustacheResult)
						try {
							message = JSON.parse(mustacheResult)
							if (cares.ping) {
								if (!message.content) {
									message.content = cares.ping
								} else {
									message.content += cares.ping
								}
							}
						} catch (err) {
							this.log.error(`${logReference}: Error JSON parsing mustache results ${mustacheResult}`, err)
						}
					}
				}

				if (!message) {
					message = { content: `*Poracle*: An alert was triggered with invalid or missing message template - ref: ${logReference}\nid: '${cares.template}' type: '${templateType}' platform: '${platform}' language: '${language}'` }
				}
				const work = {
					lat: data.latitude.toString().substring(0, 8),
					lon: data.longitude.toString().substring(0, 8),
					message,
					target: cares.id,
					type: cares.type,
					name: cares.name,
					tth: weatherTth,
					clean: cares.clean,
					emoji: [],
					logReference,
					language,
				}
				jobs.push(work)
			}

			this.log.info(`${logReference}: Weather change alert generated for ${jobs.length} humans`)
			return jobs
		} catch (e) {
			this.log.error('Weather handleMatched error: ', e, data)
		}
	}
}

module.exports = Weather
